use [WWI-DW]


Go


CREATE OR ALTER PROCEDURE FILL_WAREHOUSE_MART(@DATE date , @FIRSTLOAD BIT = 0) AS
BEGIN
    
    EXEC [WWI-Staging].[dbo].FILL_WAREHOUSE_STAGING_AREA @FIRSTLOAD;
    EXEC WAREHOUSE_DIMENSIONS_SCD_ETL;
    EXEC FILL_WAREHOUSE_FACTS @DATE , @FIRSTLOAD;

END
Go