USE [master]
GO

-- Uncomment the ALTER DATABASE statement below to set the database to SINGLE_USER mode if the drop database command fails because the database is in use.
-- ALTER DATABASE [WWI-DW] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
-- Drop the database if it exists
IF EXISTS (
  SELECT name
   FROM sys.databases
   WHERE name = N'WWI-DW'
)
DROP DATABASE [WWI-DW]
GO

/****** Object:  Database [WWI-DW]    Script Date: 1/31/2021 1:31:35 PM ******/
CREATE DATABASE [WWI-DW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WWI-DW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WWI-DW.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WWI-DW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WWI-DW_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WWI-DW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WWI-DW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WWI-DW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WWI-DW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WWI-DW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WWI-DW] SET ARITHABORT OFF 
GO

ALTER DATABASE [WWI-DW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WWI-DW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WWI-DW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WWI-DW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WWI-DW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WWI-DW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WWI-DW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WWI-DW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WWI-DW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WWI-DW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WWI-DW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WWI-DW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WWI-DW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WWI-DW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WWI-DW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WWI-DW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WWI-DW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WWI-DW] SET RECOVERY FULL 
GO

ALTER DATABASE [WWI-DW] SET  MULTI_USER 
GO

ALTER DATABASE [WWI-DW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WWI-DW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WWI-DW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WWI-DW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WWI-DW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WWI-DW] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [WWI-DW] SET QUERY_STORE = OFF
GO

ALTER DATABASE [WWI-DW] SET  READ_WRITE 
GO

